version: '2'
services:
    pgadmin-emdias:
            container_name: pgadim-emdias
            image: dpage/pgadmin4
            environment:
                - PGADMIN_DEFAULT_EMAIL=edney.chantal@gmail.com
                - PGADMIN_DEFAULT_PASSWORD=123
            ports:
                - 15432:80

    emdias:
            container_name: emdias
            image: emdias
            depends_on:
                - jhipster-registry-emdias
            links:
                - jhipster-registry-emdias:jhipster-registry
            environment:
                - SPRING_PROFILES_ACTIVE=prod
                - spring.datasource.url=jdbc:postgresql://motty.db.elephantsql.com:5432/mvtpiaib
                - spring.datasource.username=mvtpiaib
                - spring.datasource.password=yRDTvIRmzlypqygqQTrhF4scJ_puSRHu
                - JAVA_OPTS=-Xms128m -Xmx256m
                - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
                - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config

                - JHIPSTER_SLEEP=30
            ports:
                - 8081:8081


    jhipster-registry-emdias:
            container_name: jhipster-registry-emdias
            image: jhipster/jhipster-registry:v6.3.0
            volumes:
                - ./central-server-config:/central-config
     # When run with the "dev" Spring profile, the JHipster Registry will
     # read the config from the local filesystem (central-server-config directory)
     # When run with the "prod" Spring profile, it will read the configuration from a Git repository
     # See https://www.jhipster.tech/jhipster-registry/#spring-cloud-config
            environment:
                - _JAVA_OPTIONS=-Xmx512m -Xms256m
                - SPRING_PROFILES_ACTIVE=dev,swagger
                - SPRING_SECURITY_USER_PASSWORD=admin
                - JHIPSTER_REGISTRY_PASSWORD=admin
                - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
                - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/localhost-config/
       # - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=git
       # - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_URI=https://github.com/jhipster/jhipster-registry/
       # - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_PATHS=central-config
            ports:
                 - 8761:8761

    postgres-emdias:
            container_name: postgres-emdias
            image: postgres
            volumes:
                - /home/eschantal/desenvolvimento/myproject/filedatabase:/filedatabase
            environment:
                - DB_NAME=emdias
                - POSTGRES_USER=emdias
                - POSTGRES_PASSWORD=emdias
                - JAVA_OPTS=-Xms128m -Xmx256m
                - POSTGRES_HOST_AUTH_METHOD=trust
            ports:
                - 5432:5432
